-- Apply in the Supabase SQL editor as the database owner. No secret values here.
create extension if not exists pgcrypto;
create type public.lesson_status as enum ('draft','ai_generated','under_review','approved','published','archived');
create table public.profiles(id uuid primary key references auth.users on delete cascade, role text not null default 'student' check(role in ('student','volunteer','admin')), display_name text default 'Explorer', created_at timestamptz default now(), updated_at timestamptz default now());
create function public.new_profile() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id) values(new.id);return new;end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.new_profile();
insert into public.profiles(id) select id from auth.users on conflict(id) do nothing;
create function public.my_role() returns text language sql stable security definer set search_path=public as $$ select coalesce((select role from profiles where id=auth.uid()),'student') $$;
create table public.workshops(id uuid primary key default gen_random_uuid(), title text not null, created_by uuid references profiles, created_at timestamptz default now(),updated_at timestamptz default now());
create table public.journeys(id text primary key, workshop_id uuid references workshops, title text not null, created_by uuid references profiles,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.source_materials(id text primary key, created_by uuid references profiles not null, filename text not null, storage_path text, payload jsonb not null, origin text default 'imported',created_at timestamptz default now(),updated_at timestamptz default now());
create table public.source_chunks(id uuid primary key default gen_random_uuid(),source_material_id text references source_materials on delete cascade, chunk_index integer not null, page integer, text text not null, unique(source_material_id,chunk_index));
create table public.lessons(id text primary key,created_by uuid references profiles,status lesson_status not null default 'draft',version integer not null default 1 check(version>0),payload jsonb not null,created_at timestamptz default now(),updated_at timestamptz default now(), check(payload->>'id'=id),check((payload->>'version')::integer=version),check(payload->>'status'=status::text));
create table public.published_versions(lesson_id text references lessons,version integer,payload jsonb not null,published_by uuid references profiles,created_at timestamptz default now(),primary key(lesson_id,version));
create table public.vocabulary(id text,lesson_id text references lessons on delete cascade,traditional text not null,jyutping text not null,english text not null,payload jsonb not null,created_at timestamptz default now(),updated_at timestamptz default now(),primary key(lesson_id,id));
create table public.exercises(id text,lesson_id text references lessons on delete cascade,type text not null,payload jsonb not null,created_at timestamptz default now(),updated_at timestamptz default now(),primary key(lesson_id,id));
create table public.lesson_exercises(lesson_id text references lessons on delete cascade,exercise_id text,position integer not null,primary key(lesson_id,exercise_id),foreign key(lesson_id,exercise_id) references exercises(lesson_id,id) on delete cascade);
create table public.student_attempts(id uuid primary key,student_id uuid references profiles not null,lesson_id text,version integer not null,exercise_id text not null,correct boolean not null,payload jsonb not null,created_at timestamptz default now(),foreign key(lesson_id,version) references published_versions);
create table public.lesson_completions(student_id uuid references profiles,lesson_id text,version integer,payload jsonb not null,created_at timestamptz default now(),primary key(student_id,lesson_id,version),foreign key(lesson_id,version) references published_versions);
create table public.student_mastery(student_id uuid references profiles,word text,correct_count integer default 0,total_count integer default 0,last_reviewed timestamptz,primary key(student_id,word));
create table public.ai_generations(id uuid primary key default gen_random_uuid(),created_by uuid references profiles,source_material_id text references source_materials,lesson_id text references lessons,provider_mode text not null,created_at timestamptz default now());
create table public.content_reports(id uuid primary key,student_id uuid references profiles,lesson_id text references lessons,reason text not null check(length(reason)<=1000),status text default 'open',created_at timestamptz default now());
-- Ownership and role changes cannot be made through profile APIs.
alter table profiles enable row level security;
create policy own_profile on profiles for select to authenticated using(id=auth.uid() or my_role()='admin');
-- Admins assign roles through a trusted administrative SQL workflow; no public UPDATE policy.
alter table lessons enable row level security;
create policy lesson_read on lessons for select to authenticated using(status='published' or created_by=auth.uid() or my_role()='admin');
create policy lesson_create on lessons for insert to authenticated with check(created_by=auth.uid() and my_role() in ('volunteer','admin') and status in ('draft','ai_generated','under_review','approved'));
create policy lesson_edit on lessons for update to authenticated using((created_by=auth.uid() and my_role()='volunteer' and status not in ('archived')) or my_role()='admin') with check((created_by=auth.uid() and my_role()='volunteer' and status in ('draft','ai_generated','under_review','approved')) or (my_role()='admin' and status<>'published'));
create function public.journey_available(journey_id text) returns boolean language sql stable security definer set search_path=public as $$ select coalesce((select status<>'archived' from lessons where id=journey_id),false) $$;
alter table published_versions enable row level security;
create policy published_read on published_versions for select to authenticated using(journey_available(lesson_id) and (payload->>'availability'='available' or (payload->>'availableAt')::timestamptz<=now()) or exists(select 1 from lessons l where l.id=lesson_id and (l.created_by=auth.uid() or my_role()='admin')));
create function public.publish_lesson(lesson_id text) returns jsonb language plpgsql security definer set search_path=public as $$ declare item lessons%rowtype; published jsonb;begin
 select * into item from lessons where id=lesson_id for update;
 if not found or my_role() not in ('volunteer','admin') or (item.created_by is distinct from auth.uid() and my_role()<>'admin') or item.status<>'approved' then raise exception 'Reviewed volunteer approval required';end if;
 published=jsonb_set(jsonb_set(item.payload,'{status}','"published"'),'{updatedAt}',to_jsonb(now()::text));
 insert into published_versions(lesson_id,version,payload,published_by) values(item.id,item.version,published,auth.uid());
 update lessons set status='published',payload=published,updated_at=now() where id=item.id;
 return published;end $$;
revoke all on function public.publish_lesson(text) from public;grant execute on function public.publish_lesson(text) to authenticated;
-- Normalized indexes are regenerated from validated lesson content at each draft save.
create function public.index_lesson() returns trigger language plpgsql security definer set search_path=public as $$ declare v jsonb;e jsonb;i integer=0;begin
 delete from lesson_exercises where lesson_id=new.id;delete from vocabulary where lesson_id=new.id;delete from exercises where lesson_id=new.id;
 for v in select * from jsonb_array_elements(new.payload->'vocabulary') loop insert into vocabulary(id,lesson_id,traditional,jyutping,english,payload) values(v->>'id',new.id,v->>'traditional',v->>'jyutping',v->>'english',v);end loop;
 for e in select * from jsonb_array_elements(new.payload->'exercises') loop insert into exercises(id,lesson_id,type,payload) values(e->>'id',new.id,e->>'type',e);insert into lesson_exercises values(new.id,e->>'id',i);i=i+1;end loop;return new;end $$;
create trigger index_lesson_content after insert or update on lessons for each row execute function index_lesson();
create function public.index_source() returns trigger language plpgsql security definer set search_path=public as $$ declare c jsonb;begin for c in select * from jsonb_array_elements(new.payload->'chunks') loop insert into source_chunks(source_material_id,chunk_index,page,text) values(new.id,(c->>'index')::integer,(c->>'page')::integer,c->>'text');end loop;return new;end $$;
create trigger index_source_content after insert on source_materials for each row execute function index_source();
-- Recompute answer correctness inside PostgreSQL too: client submissions cannot award arbitrary XP.
create function public.validate_attempt() returns trigger language plpgsql security definer set search_path=public as $$ declare e jsonb; expected text; submitted text; counter integer;begin
 select x into e from published_versions p,jsonb_array_elements(p.payload->'exercises') x where p.lesson_id=new.lesson_id and p.version=new.version and (p.payload->>'availability'='available' or (p.payload->>'availableAt')::timestamptz<=now()) and x->>'id'=new.exercise_id;
 if e is null or not journey_available(new.lesson_id) then raise exception 'Unknown or unavailable exercise';end if;
 expected=regexp_replace(normalize(coalesce(e->>'answer',''),NFKC),'[[:space:]。，！？,.!?、]','','g');submitted=regexp_replace(normalize(coalesce(new.payload->>'answer',''),NFKC),'[[:space:]。，！？,.!?、]','','g');
 if e->>'type'='match' then new.correct=((new.payload->>'answer')::jsonb=e->'pairs');elsif e->>'type' in ('flashcard','speak','ai_roleplay') then new.correct=false;else new.correct=(lower(submitted)=lower(expected));end if;
 select count(*)+1 into counter from student_attempts where student_id=new.student_id and lesson_id=new.lesson_id and version=new.version and exercise_id=new.exercise_id;
 new.payload=jsonb_set(jsonb_set(jsonb_set(new.payload,'{correct}',to_jsonb(new.correct)),'{studentId}',to_jsonb(new.student_id::text)),'{attemptCount}',to_jsonb(counter));
 new.payload=new.payload||jsonb_build_object('id',new.id,'lessonId',new.lesson_id,'exerciseId',new.exercise_id,'version',new.version);
 new.payload=jsonb_set(new.payload,'{tags}',case when e->>'type' in ('flashcard','speak','ai_roleplay') then '[]'::jsonb else e->'tags' end);new.payload=jsonb_set(new.payload,'{timestamp}',to_jsonb(now()::text));return new;end $$;
create trigger verify_answer before insert on student_attempts for each row execute function validate_attempt();
create function public.update_mastery() returns trigger language plpgsql security definer set search_path=public as $$ declare tag text;begin for tag in select jsonb_array_elements_text(new.payload->'tags') loop insert into student_mastery(student_id,word,correct_count,total_count,last_reviewed) values(new.student_id,tag,case when new.correct then 1 else 0 end,1,now()) on conflict(student_id,word) do update set correct_count=student_mastery.correct_count+excluded.correct_count,total_count=student_mastery.total_count+1,last_reviewed=now();end loop;return new;end $$;
create trigger mastery_after_attempt after insert on student_attempts for each row execute function update_mastery();
create function public.validate_completion() returns trigger language plpgsql security definer set search_path=public as $$ begin if exists(select 1 from published_versions p,jsonb_array_elements(p.payload->'exercises') e where p.lesson_id=new.lesson_id and p.version=new.version and not exists(select 1 from student_attempts a where a.student_id=new.student_id and a.lesson_id=new.lesson_id and a.version=new.version and a.exercise_id=e->>'id')) then raise exception 'Finish each activity before completion';end if;new.payload=jsonb_build_object('studentId',new.student_id,'lessonId',new.lesson_id,'version',new.version,'timestamp',now());return new;end $$;
create trigger verify_completion before insert on lesson_completions for each row execute function validate_completion();
alter table student_attempts enable row level security;create policy attempt_read on student_attempts for select to authenticated using(student_id=auth.uid());create policy attempt_insert on student_attempts for insert to authenticated with check(student_id=auth.uid());
alter table lesson_completions enable row level security;create policy completion_read on lesson_completions for select to authenticated using(student_id=auth.uid());create policy completion_insert on lesson_completions for insert to authenticated with check(student_id=auth.uid());
alter table student_mastery enable row level security;create policy mastery_read on student_mastery for select to authenticated using(student_id=auth.uid());
alter table source_materials enable row level security;create policy source_read on source_materials for select to authenticated using(created_by=auth.uid() or my_role()='admin');create policy source_insert on source_materials for insert to authenticated with check(created_by=auth.uid() and my_role() in ('volunteer','admin'));
alter table source_chunks enable row level security;create policy chunk_read on source_chunks for select to authenticated using(exists(select 1 from source_materials s where s.id=source_material_id));
alter table ai_generations enable row level security;create policy generation_read on ai_generations for select to authenticated using(created_by=auth.uid() or my_role()='admin');create policy generation_insert on ai_generations for insert to authenticated with check(created_by=auth.uid() and my_role() in ('volunteer','admin'));
alter table content_reports enable row level security;create policy report_insert on content_reports for insert to authenticated with check(student_id=auth.uid());create policy report_read on content_reports for select to authenticated using(student_id=auth.uid() or my_role()='admin');
alter table workshops enable row level security;create policy workshop_read on workshops for select to authenticated using(created_by=auth.uid() or my_role()='admin');create policy workshop_write on workshops for insert to authenticated with check(created_by=auth.uid() and my_role() in ('volunteer','admin'));
alter table journeys enable row level security;create policy journey_read on journeys for select to authenticated using(created_by=auth.uid() or my_role()='admin');
alter table vocabulary enable row level security;create policy vocabulary_read on vocabulary for select to authenticated using(exists(select 1 from lessons l where l.id=lesson_id));
alter table exercises enable row level security;create policy exercise_read on exercises for select to authenticated using(exists(select 1 from lessons l where l.id=lesson_id));
alter table lesson_exercises enable row level security;create policy lesson_exercise_read on lesson_exercises for select to authenticated using(exists(select 1 from lessons l where l.id=lesson_id));
-- Private storage for a future file-retention option. MVP retains extracted text only.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('workshop-materials','workshop-materials',false,5242880,array['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.presentationml.presentation','text/plain','text/markdown']) on conflict(id) do nothing;
create policy own_workshop_files on storage.objects for all to authenticated using(bucket_id='workshop-materials' and (storage.foldername(name))[1]=auth.uid()::text and public.my_role() in ('volunteer','admin')) with check(bucket_id='workshop-materials' and (storage.foldername(name))[1]=auth.uid()::text and public.my_role() in ('volunteer','admin'));
-- Aggregate only the volunteer's workshops, with no student identifiers returned.
create function public.workshop_analytics() returns jsonb language plpgsql security definer set search_path=public as $$ declare result jsonb; begin
 if my_role() not in ('volunteer','admin') then raise exception 'Volunteer access required';end if;
 with scoped as (select a.* from student_attempts a join lessons l on a.lesson_id=l.id where l.created_by=auth.uid() or my_role()='admin'),
 starts as (select distinct student_id,lesson_id from scoped),
 completions as (select c.* from lesson_completions c join lessons l on c.lesson_id=l.id where l.created_by=auth.uid() or my_role()='admin'),
 words as (select tag,round(avg(case when s.correct then 100 else 0 end)) score,count(*) attempts from scoped s,jsonb_array_elements_text(s.payload->'tags') tag group by tag)
 select jsonb_build_object('students',(select count(distinct student_id) from scoped),'attempts',(select count(*) from scoped),'completion',case when (select count(*) from starts)=0 then 0 else round(100.0*(select count(*) from (select distinct student_id,lesson_id from completions) c)/(select count(*) from starts)) end,'averageAttempts',case when (select count(*) from scoped)=0 then 0 else round((select count(*) from scoped)::numeric/greatest(1,(select count(*) from(select distinct student_id,lesson_id,exercise_id from scoped) u)),1) end,'difficult',coalesce((select jsonb_agg(jsonb_build_object('word',tag,'score',score,'attempts',attempts)) from(select * from words order by score limit 3) w),'[]'::jsonb)) into result;return result;end $$;
revoke all on function public.workshop_analytics() from public;grant execute on function public.workshop_analytics() to authenticated;
